name: "Setup OpenSeesPy"
description: "Install OpenSeesPy and dependencies"

branding:
  icon: "package"
  color: "blue"

inputs:
  version:
    description: "openseespy version"
    required: false
    default: "latest"

  opsvis:
    description: "Install opsvis package"
    required: false
    default: "false"

runs:
  using: "composite"

  steps:
    - name: Install OpenSeesPy on Linux
      if: runner.os == 'Linux'
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y libblas-dev # Required for some versions of OpenSeesPy

        python -m pip install --upgrade pip

        if [ "${{ inputs.version }}" = "latest" ]; then
          python -m pip install openseespy
        else
          python -m pip install openseespy==${{ inputs.version }}
          # Force install openseespylinux in case the wrapper does not enforce versions
          python3 -m pip install openseespylinux==${{ inputs.version }}
        fi

        if [ "${{ inputs.opsvis }}" = "true" ]; then
          python -m pip install opsvis
        fi

    - name: Install OpenSeesPy on macOS
      if: runner.os == 'macOS'
      shell: bash
      run: |
        python -m pip install --upgrade pip

        if [ "${{ inputs.version }}" = "latest" ]; then
          python -m pip install openseespy
        else
          python -m pip install openseespy==${{ inputs.version }}
          # Force install openseespymac in case the wrapper does not enforce versions
          python3 -m pip install openseespymac==${{ inputs.version }}
        fi

        if [ "${{ inputs.opsvis }}" = "true" ]; then
          python -m pip install opsvis
        fi

    - name: Install OpenSeesPy on Windows
      if: runner.os == 'Windows'
      shell: pwsh
      run: |
        python -m pip install --upgrade pip

        if ("${{ inputs.version }}" -eq "latest") {
          python -m pip install openseespy
        }
        else {
          python -m pip install openseespy==${{ inputs.version }} 
          # Force install openseespywin in case the wrapper does not enforce versions
          python -m pip install openseespywin==${{ inputs.version }}
        }

        if ("${{ inputs.opsvis }}" -eq "true") {
          python -m pip install opsvis
        }

    - name: Print installed versions
      shell: bash
      run: |
        python --version

        python -c "import openseespy.opensees as ops; print('OpenSeesPy:', ops.version())"
